<!-- <h1>aaaaaaaaaa</h1>
<!-- <div id="bodyContent" class="vector-body ve-init-mw-desktopArticleTarget-targetContainer" aria-labelledby="firstHeading" data-mw-ve-target-container="">
					<div class="vector-body-before-content">
							<div class="mw-indicators">
		</div>

						<div id="siteSub" class="noprint">De Wikipedia, la enciclopedia libre</div>
					</div>
					<div id="contentSub"><div id="mw-content-subtitle"></div></div>
					
					
					<div id="mw-content-text" class="mw-body-content"><div class="mw-content-ltr mw-parser-output" lang="es" dir="ltr"><figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Lueger.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Lueger.jpg/220px-Lueger.jpg" decoding="async" width="220" height="151" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Lueger.jpg/330px-Lueger.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Lueger.jpg/440px-Lueger.jpg 2x" data-file-width="1568" data-file-height="1074"></a><figcaption><a href="/wiki/Lexikon_der_gesamten_Technik" title="Lexikon der gesamten Technik">Lexikon der gesamten Technik</a> de Otto Lueger, una enciclopedia de tecnología.</figcaption></figure>
<p><b>Enciclopedia</b> (en <a href="/wiki/Idioma_griego" title="Idioma griego">griego</a>, <span lang="grc" title="Texto en idioma griego antiguo">ἐνκύκλιoς παιδεία</span>, <i>enkyklios paideia</i>, «círculo de la instrucción, educación redonda»)<sup id="cite_ref-1" class="reference separada"><a href="#cite_note-1"><span class="corchete-llamada">[</span>1<span class="corchete-llamada">]</span></a></sup>​<sup id="cite_ref-2" class="reference separada"><a href="#cite_note-2"><span class="corchete-llamada">[</span>2<span class="corchete-llamada">]</span></a></sup>​ es el <a href="/wiki/G%C3%A9nero_literario" title="Género literario">género literario</a>, clasificado como <a href="/wiki/G%C3%A9nero_did%C3%A1ctico" title="Género didáctico">didáctico</a>, el cual es una <a href="/wiki/Obra_de_referencia" title="Obra de referencia">obra de referencia</a> que recopila y compendia el <a href="/wiki/Conocimiento" title="Conocimiento">conocimiento</a> humano,<sup id="cite_ref-3" class="reference separada"><a href="#cite_note-3"><span class="corchete-llamada">[</span>3<span class="corchete-llamada">]</span></a></sup>​de forma temática, en orden alfabético, con una pretensión objetiva, imparcial y universal (no especializada, monotemática o subjetiva, a diferencia de un <a href="/wiki/Tratado" title="Tratado">tratado</a>, o de un <a href="/wiki/Ensayo" title="Ensayo">ensayo</a>).
</p><p>Las enciclopedias  han aportado un importante servicio a la cultura moderna, al permitir hallar en toda la historia y con facilidad los conocimientos esenciales para casi cualquier objeto o actividad.<sup id="cite_ref-4" class="reference separada"><a href="#cite_note-4"><span class="corchete-llamada">[</span>4<span class="corchete-llamada">]</span></a></sup>​<sup id="cite_ref-5" class="reference separada"><a href="#cite_note-5"><span class="corchete-llamada">[</span>5<span class="corchete-llamada">]</span></a></sup>​
</p><p>Según Katz W., la enciclopedia es una obra que contiene información sobre todas las materias en la mayor parte de los campos del conocimiento.
</p><p>La noción más moderna en Occidente de enciclopedia de propósito general y de amplia distribución data de la época de <a href="/wiki/Ephraim_Chambers" title="Ephraim Chambers">Ephraim Chambers</a> y su <i><a href="/wiki/Cyclopaedia" title="Cyclopaedia">Cyclopaedia</a></i> (1728). Luego le sucederían <a href="/wiki/Denis_Diderot" title="Denis Diderot">Denis Diderot</a> y los <a href="/wiki/Enciclopedistas_del_siglo_XVIII" class="mw-redirect" title="Enciclopedistas del siglo XVIII">enciclopedistas del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XVIII</span></a> que se inspiraron en la <i>Cyclopaedia</i> de Chambers, creando el mayor hito del periodo de la <a href="/wiki/Ilustraci%C3%B3n" title="Ilustración">Ilustración</a> del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XVIII</span>: la <i><a href="/wiki/Encyclop%C3%A9die" class="mw-redirect" title="Encyclopédie">Encyclopédie</a></i> (1751-1772), compilada por un grupo de escritores y hombres de ciencia franceses. De manera plenamente consciente, estos hombres estaban dando la espalda tanto a la <a href="/wiki/Religi%C3%B3n" title="Religión">religión</a> como a la <a href="/wiki/Metaf%C3%ADsica" title="Metafísica">metafísica</a> como fuentes de conocimiento, viendo en la <a href="/wiki/Ciencia" title="Ciencia">ciencia</a> pura y su aplicación, la <a href="/wiki/Tecnolog%C3%ADa" title="Tecnología">tecnología</a>, una nueva fuerza motriz intelectual según la ideología <a href="/wiki/Materialismo" title="Materialismo">materialista</a> y <a href="/wiki/Laicismo" title="Laicismo">laicista</a> propia de la <a href="/wiki/Clase_media" title="Clase media">clase media</a> o <a href="/wiki/Burgues%C3%ADa" title="Burguesía">burguesía</a> entonces en auge. Reunieron en una vasta obra todos los conocimientos científicos de la época, no como un mero registro alfabético, sino como un relato del nuevo modo científico de interpretar el <a href="/wiki/Mundo" title="Mundo">mundo</a>.
</p>
<meta property="mw:PageProp/toc">
<div class="mw-heading mw-heading2"><h2 id="Historia">Historia</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=1" title="Editar sección: Historia"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<div class="mw-heading mw-heading3"><h3 id="Orígenes"><span id="Or.C3.ADgenes"></span>Orígenes</h3><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=2" title="Editar sección: Orígenes"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<p>Origen: Préstamo (siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XV</span>) del latín medieval <i>dictionarium</i>, derivado de <i>dictio</i>, <i>dictionis</i> ‘dicción’. De la familia etimológica de <i>decir</i> (V.).<sup id="cite_ref-6" class="reference separada"><a href="#cite_note-6"><span class="corchete-llamada">[</span>6<span class="corchete-llamada">]</span></a></sup>​
</p><p>En <a href="/wiki/Sumeria" title="Sumeria">Sumeria</a>, durante el cuarto milenio antes de Cristo se redactó un <a href="/wiki/Glosario" title="Glosario">glosario</a> temático o por temas como un primer intento de ordenar o catalogar el conocimiento del <a href="/wiki/Mundo" title="Mundo">mundo</a>, y 600 años después se registra un intento similar en <a href="/wiki/Ebla" title="Ebla">Ebla</a> siguiendo un orden convencional de signos; estos primeros intentos se denominan <a href="/wiki/Listas_lexicales" class="mw-redirect" title="Listas lexicales">listas lexicales</a>.
</p><p>En el <a href="/wiki/Egipto" title="Egipto">Egipto</a> antiguo se encuentran igualmente unas listas temáticas que se pueden considerar como protoenciclopedias. La <i>Onomástica del <a href="/wiki/Ramesseum" title="Ramesseum">Ramesseum</a></i>, redactada hacia 1750a.C. es una lista de palabras agrupadas por categorías. Otra obra del mismo género, pero mucho más desarrollada, es la <i>Onomástica de <a href="/wiki/Amenofis" class="mw-redirect" title="Amenofis">Amenofis</a></i>, realizada hacia 1100. Cuenta con 610 elementos organizados de modo temático y contendría más de 2000 informaciones distintas con la ambición de crear «un catálogo sistemático del <a href="/wiki/Universo" title="Universo">universo</a>». Este lejano ancestro del <a href="/wiki/Diccionario" title="Diccionario">diccionario</a> enciclopédico tendría el cometido «no de enseñar a escribir a los niños, sino de proponer un programa de <a href="/wiki/Educaci%C3%B3n" title="Educación">instrucción</a> de la <a href="/wiki/Ser_humano" class="mw-redirect" title="Ser humano">humanidad</a> fundado sobre la organización del <a href="/wiki/Mundo" title="Mundo">mundo</a>».
</p>
<figure class="mw-default-size mw-halign-left" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Naturalishistoria.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/6/67/Naturalishistoria.jpg/220px-Naturalishistoria.jpg" decoding="async" width="220" height="371" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/6/67/Naturalishistoria.jpg 1.5x" data-file-width="235" data-file-height="396"></a><figcaption>Edición de <i>Naturalis Historiæ</i> de 1669; la obra no sigue el formato moderno de enciclopedia, pues <a href="/wiki/Plinio_el_Viejo" title="Plinio el Viejo">Plinio</a> ordena los artículos por áreas, como un grupo coherente y en forma de guía, siguiendo la clasificación de la naturaleza de <a href="/wiki/Arist%C3%B3teles" title="Aristóteles">Aristóteles</a> (animal, vegetal, mineral), para así recrear una visión del mundo natural en forma más literaria y comprensiva.</figcaption></figure>
<p>El filósofo griego <a href="/wiki/Plat%C3%B3n" title="Platón">Platón</a> (428-348&nbsp;a.&nbsp;C.) realizó un resumen de los conocimientos de su época en uno de sus diálogos, el <i><a href="/wiki/Timeo" title="Timeo">Timeo</a></i>: Astronomía, Cosmogonía, Física y Medicina. Esta obra puede ser considerada una "enciclopedia metódica". Su discípulo <a href="/wiki/Arist%C3%B3teles" title="Aristóteles">Aristóteles</a> (384-322) produjo una larga cantidad de tratados sobre gran variedad de temas con un espíritu verdaderamente enciclopédico y sin equivalentes en el mundo antiguo (Poética, Retórica, Lógica, Política, Física, Psicología, Biología, Ética...). Sin embargo, sus esfuerzos no fueron difundidos hasta 275 años después de su fallecimiento, hacia el año 50&nbsp;a.&nbsp;C.. Se perdió prácticamente toda la obra de escritores enciclopédicos como <a href="/wiki/Dem%C3%B3crito" title="Demócrito">Demócrito</a> y <a href="/wiki/Posidonio" title="Posidonio">Posidonio</a>.
</p><p>Entre los romanos, el primero en intentar compendiar el saber antiguo fue <a href="/wiki/Marco_Terencio_Varr%C3%B3n" class="mw-redirect" title="Marco Terencio Varrón">Varrón</a> (116-27&nbsp;a.&nbsp;C.), cuyas <i>Antiquitatum rerum humanarum et divinarum libri XLI</i> no han perdurado sino como fragmentos y extractos en otros autores y enciclopedistas posteriores. Para este autor, el camino al saber era la <a href="/wiki/Etimolog%C3%ADa" title="Etimología">etimología</a>, como lo fue para el muy posterior visigodo <a href="/wiki/San_Isidoro" class="mw-redirect" title="San Isidoro">san Isidoro</a>, probablemente el último en servirse de esta perdida obra de Varrón para su propia enciclopedia, las <i>Etimologías</i>. Para Varrón el término <i>verbum</i> («&nbsp;palabra») venía de <i>veritas</i> («&nbsp;verdad»), lo que legitimaba ese procedimiento. Compuesta esta obra por 41 libros, 25 estaban consagrados a los asuntos humanos y el resto a los divinos de los dioses paganos. Esta obra, desaparecida, dejó, sin embargo, mucho conocimiento a través de sus citas y diversas refundiciones medievales.
</p><p>Hacia el comienzo del primer siglo de nuestra era, <a href="/wiki/Aulo_Cornelio_Celso" title="Aulo Cornelio Celso">Aulo Cornelio Celso</a> redactó una enciclopedia en 26 libros, <i>De Artibus</i>, que cubría materias de Agricultura, Guerra, Retórica, Filosofía, Derecho y Medicina, si bien fue este último dominio el más particularmente desarrollado, precisamente la única sección de la obra que ha llegado hasta nosotros, al menos en parte.
</p><p>Posterior y una de las primeras obras enciclopédicas que han sobrevivido a los tiempos modernos, es la <i><a href="/wiki/Naturalis_Historia" class="mw-redirect" title="Naturalis Historia">Naturalis Historia</a></i> de <a href="/wiki/Plinio_el_Viejo" title="Plinio el Viejo">Plinio el Viejo</a>, escritor romano del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">I</span>&nbsp;d.&nbsp;C. Compiló una obra de 37 capítulos que abarcan la historia natural del arte y la arquitectura, la medicina, la geografía, la geología y todos los aspectos del mundo que le rodeaba. Declaró en su prólogo que había compilado veinte mil hechos a partir de dos mil títulos de doscientos autores distintos, y agregó que otros muchos provenían de su propia experiencia. El trabajo fue publicado alrededor de 77 a 79&nbsp;d.&nbsp;C.,<sup id="cite_ref-7" class="reference separada"><a href="#cite_note-7"><span class="corchete-llamada">[</span>7<span class="corchete-llamada">]</span></a></sup>​ pero probablemente nunca terminó de corregir la obra antes de que falleciera investigando la erupción del <a href="/wiki/Vesubio" class="mw-redirect" title="Vesubio">Vesubio</a> en 79&nbsp;d.&nbsp;C.
</p>
<figure class="mw-default-size mw-halign-left" typeof="mw:File/Thumb"><a href="/w/index.php?title=Archivo:MargaritaPhilosophica.djvu&amp;page=4" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/MargaritaPhilosophica.djvu/page4-220px-MargaritaPhilosophica.djvu.jpg" decoding="async" width="220" height="294" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/e3/MargaritaPhilosophica.djvu/page4-330px-MargaritaPhilosophica.djvu.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/e3/MargaritaPhilosophica.djvu/page4-440px-MargaritaPhilosophica.djvu.jpg 2x" data-file-width="1024" data-file-height="1424"></a><figcaption>La filosofía <i>triceps</i> (<i>naturalis</i>, <i>rationalis</i> y <i>moralis</i>) con las siete <a href="/wiki/Artes_liberales" title="Artes liberales">artes liberales</a>, <a href="/wiki/Xilograf%C3%ADa" title="Xilografía">xilografía</a> que sirve de frontispicio a la primera edición de la primera enciclopedia impresa, la <i>Margarita philosophica</i> de <a href="/wiki/Gregor_Reisch" title="Gregor Reisch">Gregor Reisch</a>, 1503.</figcaption></figure>
<p>En sus <i><a href="/wiki/Noches_%C3%81ticas_(Aulo_Gelio)" class="mw-redirect" title="Noches Áticas (Aulo Gelio)">Noches áticas</a></i> (II siglo&nbsp;d.&nbsp;C.), <a href="/wiki/Aulo_Gelio" title="Aulo Gelio">Aulo Gelio</a> diserta sobre numerosas materias de literatura, artes, filosofía, historia, derecho, geometría, medicina, ciencias naturales, meteorología y geografía, aunque con un espíritu más ensayístico y erudito que sistemático y enciclopédico.
Por otra parte, el <i>Polyhistor</i> (también llamado <i>Las maravillas del mundo</i>), obra del escritor romano <a href="/wiki/Solino" class="mw-redirect" title="Solino">Solino</a>, del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">III</span> o <span style="font-variant:small-caps;text-transform:lowercase">IV</span>&nbsp;a.&nbsp;C. presenta las curiosidades del mundo por regiones. Aunque la obra se ha perdido, numerosos elementos de ella, como en el caso de Varrón, fueron recogidos en las enciclopedias medievales.
<a href="/wiki/Nonio_Marcelo" title="Nonio Marcelo">Nonio Marcelo</a> redactó, a comienzos del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">IV</span>, el <i>De compendiosa doctrina</i>, una compilación o <a href="/wiki/Ep%C3%ADtome" title="Epítome">epítome</a> de tratados sobre la lengua y diversas técnicas, arreglada y ordenada en forma alfabética. Hacia fines del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">IV</span>, el gramático <a href="/wiki/Mario_Servio_Honorato" class="mw-redirect" title="Mario Servio Honorato">Servio</a> redactó un muy abundante comentario a la obra de <a href="/wiki/Virgilio" title="Virgilio">Virgilio</a> que puede leerse también como un vasto repertorio temático o como una enciclopedia organizada según el orden del texto del poeta. <a href="/wiki/Marciano_Capella" title="Marciano Capella">Marciano Capella</a>, abogado que vivía en Argelia, fue autor del <i>De nuptiis Philologiae et Mercurii</i> ("Bodas de Filología y Mercurio"), redactado entre 410 y 429. Este manual en forma de narración <a href="/wiki/Alegor%C3%ADa" title="Alegoría">alegórica</a> sintetiza en 9 libros los conocimientos de la época: Filología, Gramática, Dialéctica, Retórica, Geometría, Aritmética, Astronomía y Armonía. Fue muy popular en <a href="/wiki/%C3%89poca_carolingia" class="mw-redirect" title="Época carolingia">época carolingia</a>, y servirá de referencia para organizar los estudios medievales en la enseñanza básica (el <i><a href="/wiki/Trivium" title="Trivium">Trivium</a></i>) y superior (el <i><a href="/wiki/Quadrivium" title="Quadrivium">Quadrivium</a></i>). Fue leído incluso en el <a href="/wiki/Renacimiento" title="Renacimiento">Renacimiento</a> e inspiró en especial a <a href="/wiki/Cop%C3%A9rnico" class="mw-redirect" title="Copérnico">Copérnico</a>. <a href="/wiki/Rabano_Mauro" title="Rabano Mauro">Rabano Mauro</a> redactó hacia 842 su <i>De rerum naturis</i>, llamado también <i>De Universo</i> en veinte libros, resumiendo y reordenando la obra de <a href="/wiki/Isidoro_de_Sevilla" title="Isidoro de Sevilla">Isidoro de Sevilla</a>.
</p>
<div class="mw-heading mw-heading3"><h3 id="Edad_Media_y_Moderna">Edad Media y Moderna</h3><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=3" title="Editar sección: Edad Media y Moderna"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg/220px-San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg" decoding="async" width="220" height="156" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8e/San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg/330px-San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8e/San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg/440px-San_Isidoro_Biblioteca_Nacional_Espa%C3%B1a.jpg 2x" data-file-width="2195" data-file-height="1557"></a><figcaption>Estatua de <a href="/wiki/Isidoro_de_Sevilla" title="Isidoro de Sevilla">Isidoro de Sevilla</a> en la escalinata de acceso a la <a href="/wiki/Biblioteca_Nacional_de_Espa%C3%B1a" title="Biblioteca Nacional de España">Biblioteca Nacional de España</a>.</figcaption></figure>
<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Irakischer_Maler_von_1287_001.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Irakischer_Maler_von_1287_001.jpg/220px-Irakischer_Maler_von_1287_001.jpg" decoding="async" width="220" height="293" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Irakischer_Maler_von_1287_001.jpg/330px-Irakischer_Maler_von_1287_001.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Irakischer_Maler_von_1287_001.jpg/440px-Irakischer_Maler_von_1287_001.jpg 2x" data-file-width="1576" data-file-height="2102"></a><figcaption>Manuscrito iluminado de 1287 que muestra a los enciclopedistas musulmanes, los Hermanos de la Pureza.</figcaption></figure>
<p>Años después se crearon otras obras que eran recopilaciones o <a href="/wiki/Ep%C3%ADtome" title="Epítome">epítomes</a> (resúmenes) de conocimientos generales. Uno de los repertorios más tempranos, conocidos y famosos, de una gran amplitud y destinado a salvar los conocimientos esenciales de la cultura grecolatina clásica, es el titulado <i><a href="/wiki/Etimolog%C3%ADas" class="mw-redirect" title="Etimologías">Etimologías</a></i> compuesto por el escritor visigodo <a href="/wiki/San_Isidoro" class="mw-redirect" title="San Isidoro">San Isidoro</a> y redactado entre 627-630 a instancia del rey visigodo <a href="/wiki/Sisebuto" title="Sisebuto">Sisebuto</a>.<sup id="cite_ref-8" class="reference separada"><a href="#cite_note-8"><span class="corchete-llamada">[</span>8<span class="corchete-llamada">]</span></a></sup>​ Luego se escribieron, entre otros, los siguientes:
</p>
<ul><li>Siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">VI</span>: <i><a href="/wiki/Brihat_Samhita" class="mw-redirect" title="Brihat Samhita">Bṛihat Saṃhitā</a></i>, enciclopedia india escrita en <a href="/wiki/S%C3%A1nscrito" title="Sánscrito">sánscrito</a> por <a href="/wiki/Varaja_Mijira" title="Varaja Mijira">Varaja Mijira</a>.</li>
<li>627-630, <i><a href="/wiki/Etimolog%C3%ADas" class="mw-redirect" title="Etimologías">Etimologías</a></i> de San <a href="/wiki/Isidoro_de_Sevilla" title="Isidoro de Sevilla">Isidoro de Sevilla</a>.</li>
<li><i>c</i>. 990: <i><a href="/wiki/Suda" title="Suda">Suda</a></i> de <a href="/wiki/Suidas_(lexic%C3%B3grafo)" title="Suidas (lexicógrafo)">Suidas</a>.</li>
<li>Siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">VIII</span>. <i><a href="/wiki/Liber_glossarum" title="Liber glossarum">Liber glossarum</a></i> o <i>Glosario de Ansileubo</i>, primera enciclopedia latina en orden alfabético.</li>
<li>Siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">X</span>: <i><a href="/wiki/Hermanos_de_la_pureza" class="mw-redirect" title="Hermanos de la pureza">Epístolas de los Hermanos de la Pureza</a></i> (<i>Rasā’il Ijwān al-Safā’</i>) enciclopedia en árabe escrita en <a href="/wiki/Basora" title="Basora">Basora</a>.</li>
<li><i>c.</i> 1110: <i>Imago mundi</i> de <a href="/wiki/Honor%C3%A9_d%27Autun" class="mw-redirect" title="Honoré d'Autun">Honoré d'Autun</a>.</li>
<li>1120, <i>Liber Floridus</i> del canónigo Lamberto (Lambertus de Sancto Audomaro)</li>
<li><i>c.</i> 1180: <i><a href="/wiki/Hortus_deliciarum" title="Hortus deliciarum">Hortus deliciarum</a></i>, de <a href="/wiki/Herrada_de_Landsberg" title="Herrada de Landsberg">Herrada de Landsberg</a>.</li>
<li>1231: <i>De universo creaturarum</i> de <a href="/wiki/Guillermo_de_Auvernia" title="Guillermo de Auvernia">Guillermo de Auvernia</a>.</li>
<li>1240: <i>De proprietatibus rerum</i> de <a href="/wiki/Bartholomeus_Anglicus" class="mw-redirect" title="Bartholomeus Anglicus">Bartholomeus Anglicus</a>.</li>
<li>1256: <i>Liber de natura rerum</i> de <a href="/wiki/Thomas_de_Cantimpr%C3%A9" class="mw-redirect" title="Thomas de Cantimpré">Thomas de Cantimpré</a>, traducido al neerlandés y al alemán un siglo después.</li>
<li>12?? (siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XIII</span>): <i><a href="/wiki/Speculum_Majus" class="mw-redirect" title="Speculum Majus">Speculum Majus</a></i> de <a href="/wiki/Vincent_de_Beauvais" title="Vincent de Beauvais">Vincent de Beauvais</a>.</li>
<li>1260-1267: <i><a href="/wiki/Libros_del_tesoro" class="mw-redirect" title="Libros del tesoro">Li Livres dou Trésor</a></i> de <a href="/wiki/Brunetto_Latini" title="Brunetto Latini">Brunetto Latini</a>, primera enciclopedia medieval en romper con el latín, pronto traducida al español.</li>
<li>1295: <i>Arbor scientiae</i> de <a href="/wiki/Raimundo_Lulio" class="mw-redirect" title="Raimundo Lulio">Raimundo Lulio</a>.</li>
<li>Siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XIII</span>: <i><a href="/wiki/Lucidario" title="Lucidario">Lucidario</a></i> de <a href="/wiki/Sancho_IV_de_Castilla" title="Sancho IV de Castilla">Sancho IV</a> de Castilla.</li></ul>
<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Yongle_Dadian_Encyclopedia_1403.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yongle_Dadian_Encyclopedia_1403.jpg/220px-Yongle_Dadian_Encyclopedia_1403.jpg" decoding="async" width="220" height="198" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yongle_Dadian_Encyclopedia_1403.jpg/330px-Yongle_Dadian_Encyclopedia_1403.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yongle_Dadian_Encyclopedia_1403.jpg/440px-Yongle_Dadian_Encyclopedia_1403.jpg 2x" data-file-width="640" data-file-height="575"></a><figcaption>Enciclopedia china <i>Yongle Dadian</i> (1403).</figcaption></figure>
<ul><li>Comienzos del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XV</span>: <i>Fons memorabilium universi</i> («Fuente de maravillas del universo») de Domenico Bandini, primera obra que utiliza un sistema de referencias cruzadas.</li>
<li>1403-1407: <i><a href="/wiki/Yongle_Dadian" class="mw-redirect" title="Yongle Dadian">Yongle Dadian</a></i> (永樂大典) (durante la <a href="/wiki/Dinast%C3%ADa_Ming" title="Dinastía Ming">Dinastía Ming</a>).</li>
<li>1435: <i><a href="/wiki/Visi%C3%B3n_deleytable" class="mw-redirect" title="Visión deleytable">Visión deleytable</a></i> de <a href="/wiki/Alfonso_de_la_Torre" title="Alfonso de la Torre">Alfonso de la Torre</a>.</li>
<li>1460: <i><a href="/wiki/Invencionario" title="Invencionario">Invencionario</a></i> de Alfonso de Toledo.</li>
<li>1496: <i>Cornucopiae</i> de Niccolò Perotti, ampliadas por <a href="/wiki/Polidoro_Virgilio" title="Polidoro Virgilio">Polidoro Virgilio</a>.</li>
<li>1499: <i>De rerum inventoribus libri octo</i>, de <a href="/wiki/Polidoro_Virgilio" title="Polidoro Virgilio">Polidoro Virgilio</a>. Muy ampliados y reimpresos posteriormente.</li>
<li>1501: <i>De expetendis et fugiendis rebus</i> de Giorgio Valla.</li>
<li>1503: <i>Polyanthea</i> de Domenico Nani Mirabelli, reelaborado y ampliado en más de cuarenta ediciones entre 1503 y 1681, con una edición definitiva en 1735.</li>
<li>1503: <i>Aepitoma Omnis Philosophiae. Alias Margarita Phylosophica tractans de omne genera...</i> de <a href="/wiki/Gregor_Reisch" title="Gregor Reisch">Gregor Reisch</a>. Fue la primera enciclopedia impresa; tuvo segunda edición ampliada en Estrasburgo: Johann Gruninger, 1504; hasta 1599 sumó diez ediciones.</li>
<li>1503: <i>Officina</i> de <a href="/wiki/Jean_Tixier" class="mw-redirect" title="Jean Tixier">Jean Tixier</a>.</li>
<li>1506: <i>Commentariorum urbanorum libri XXXVIII</i> (Roma, 1506) de <a href="/wiki/Raffaele_Maffei" title="Raffaele Maffei">Raffaele Maffei</a>.</li>
<li>1517: <i>Encyclopedia orbisque doctrinarum, hoc est omnium artium, scientiarum, ipsius philosophiae index ac divisio</i>, escrita por <a href="/wiki/Johannes_Aventinus" title="Johannes Aventinus">Johannes Aventinus</a>. Es la primera obra que se titula <i>Enciclopedia</i>.</li>
<li>1519: <i>Cornucopiae, quo continentur loca diversis rebus abundantia secundum ordinem literatum</i>, París, 1519, por <a href="/wiki/Jean_Tixier" class="mw-redirect" title="Jean Tixier">Jean Tixier</a>.</li>
<li>1529: <i>Catalogus Gloriae Mundi</i> de <a href="/wiki/Barth%C3%A9lemy_de_Chasseneuz" title="Barthélemy de Chasseneuz">Barthélemy de Chasseneuz</a>.</li>
<li>1541: <i>Cyclopaedia</i> de <a href="/wiki/Joachim_Sterck_van_Ringelbergh" title="Joachim Sterck van Ringelbergh">Joachim Sterck van Ringelbergh</a>.</li>
<li>1553: <i>Dictionarium historicum, geographicum et poeticum</i> de <a href="/wiki/Charles_Estienne" title="Charles Estienne">Charles Estienne</a>.</li>
<li>1559: <i>Encyclopaedia seu orbis disciplinarum tam sacrarum quam prophanarum epistemon</i> de <a href="/wiki/Paul_Scalich" title="Paul Scalich">Paul Scalich</a>.</li>
<li>1565-1587: <i>Theatrum Humanae Vitae</i> de <a href="/wiki/Theodor_Zwinger" title="Theodor Zwinger">Theodor Zwinger</a>.</li>
<li>1572: <i>Officinae Ioannis Ravisii Textoris Epitome</i>, de <a href="/wiki/Jean_Tixier" class="mw-redirect" title="Jean Tixier">Jean Tixier</a> y otros.</li>
<li>1590: <i>Universae naturae theatrum</i>, de <a href="/wiki/Jean_Bodin" title="Jean Bodin">Jean Bodin</a>.</li>
<li>1607: <i>Polyanthea Nova</i>, de <a href="/wiki/Joseph_Lange" title="Joseph Lange">Joseph Lange</a>.</li>
<li>1620: <i>Instauratio Magna</i> (no terminado) y <i><a href="/wiki/Novum_Organum" class="mw-redirect" title="Novum Organum">Novum Organum</a></i> de <a href="/wiki/Francis_Bacon" title="Francis Bacon">Francis Bacon</a>.</li></ul>
<figure class="mw-default-size mw-halign-left" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Alsted_Encyclopaedia_1630.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Alsted_Encyclopaedia_1630.jpg/220px-Alsted_Encyclopaedia_1630.jpg" decoding="async" width="220" height="315" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/d/d2/Alsted_Encyclopaedia_1630.jpg 1.5x" data-file-width="264" data-file-height="378"></a><figcaption>Portada de la <i>Encyclopædia</i> de Johann Heinrich Alsted (Herborn, 1630).</figcaption></figure>
<ul><li>1630: <i><a href="/wiki/Encyclopaedia_Cursus_Philosophici" class="mw-redirect" title="Encyclopaedia Cursus Philosophici">Encyclopaedia Cursus Philosophici</a></i> de <a href="/wiki/Johann_Heinrich_Alsted" title="Johann Heinrich Alsted">Johann Heinrich Alsted</a>.</li>
<li>1643. <i>Pansophiae diatyposis</i> de <a href="/wiki/Comenius" class="mw-redirect" title="Comenius">Comenius</a> (el pedagogo y humanista checo <a href="/wiki/Jan_Amos_Komensk%C3%BD" class="mw-redirect" title="Jan Amos Komenský">Jan Amos Komenský</a>, 1592-1670)</li>
<li>1653-1655: <i>Enciclopedia Magyar</i> de János Apáczai Csere.</li>
<li>1668: <i>La science universelle</i> (4 vols.) de Charles Sorel.</li>
<li>1669: <i>Ars magna sive sciendi Combinatorica</i> de <a href="/wiki/Athanasius_Kircher" class="mw-redirect" title="Athanasius Kircher">Athanasius Kircher</a>.</li>
<li>1678-1681: <i>Praecognita ad Encyclopaediam sive Scientiam universalem</i> de <a href="/wiki/Gottfried_Leibniz" title="Gottfried Leibniz">Gottfried Leibniz</a>.</li>
<li>1688-1708: <i>Polyhistor literarius, philosophicus, et practicus</i> de <a href="/wiki/Daniel_Georg_Morhof" title="Daniel Georg Morhof">Daniel Georg Morhof</a>.</li>
<li>1697: <i><a href="/wiki/Dictionnaire_Historique_et_Critique" title="Dictionnaire Historique et Critique">Dictionnaire Historique et Critique</a></i> de <a href="/wiki/Pierre_Bayle" title="Pierre Bayle">Pierre Bayle</a>; segunda edición muy aumentada en 1702.</li></ul>
<div class="mw-heading mw-heading3"><h3 id="Edad_Contemporánea"><span id="Edad_Contempor.C3.A1nea"></span>Edad Contemporánea</h3><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=4" title="Editar sección: Edad Contemporánea"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg/220px-Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg" decoding="async" width="220" height="360" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg/330px-Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg/440px-Encyclopedie_de_D%27Alembert_et_Diderot_-_Premiere_Page_-_ENC_1-NA5.jpg 2x" data-file-width="3133" data-file-height="5120"></a><figcaption>Portada del libro <i><a href="/wiki/Encyclop%C3%A9die" class="mw-redirect" title="Encyclopédie">Encyclopédie</a></i> editado en 1773.</figcaption></figure>
<ul><li>1702: Segunda edición, muy aumentada, del <i><a href="/wiki/Dictionnaire_Historique_et_Critique" title="Dictionnaire Historique et Critique">Dictionnaire Historique et Critique</a></i> de <a href="/wiki/Pierre_Bayle" title="Pierre Bayle">Pierre Bayle</a>.</li>
<li>1704-1771: <i>Dictionnaire universel</i> , más conocido como <i>Diccionario de Trévoux</i>, elaborado por jesuitas franceses.</li>
<li>1704: <i><a href="/wiki/Lexicon_technicum" title="Lexicon technicum">Lexicon technicum</a></i> de <a href="/wiki/John_Harris" title="John Harris">John Harris</a>.</li>
<li>1726: <i><a href="/wiki/Gujin_tushu_jicheng" class="mw-redirect" title="Gujin tushu jicheng">Gujin tushu jicheng</a></i> (古今圖書集成), dirigida por <a href="/wiki/Chen_Menglei" title="Chen Menglei">Chen Menglei</a> (陳夢雷) por <a href="/wiki/Jiang_Tingxi" title="Jiang Tingxi">Jiang Tingxi</a> (蔣廷錫) (<a href="/wiki/Dinast%C3%ADa_Qing" title="Dinastía Qing">Dinastía Qing</a>).</li>
<li>1728: <i><a href="/wiki/Cyclopaedia" title="Cyclopaedia">Cyclopaedia</a></i> de <a href="/wiki/Ephraim_Chambers" title="Ephraim Chambers">Ephraim Chambers</a>.</li>
<li>1751-1772: La <i><a href="/wiki/Encyclop%C3%A9die" class="mw-redirect" title="Encyclopédie">Encyclopédie</a></i> dirigida por <a href="/wiki/Denis_Diderot" title="Denis Diderot">Denis Diderot</a> y <a href="/wiki/Jean_le_Rond_d%27Alembert" title="Jean le Rond d'Alembert">Jean le Rond d'Alembert</a>. Obra culmen de la <a href="/wiki/Ilustraci%C3%B3n" title="Ilustración">Ilustración</a>, su propósito fue reunir y difundir en prosa clara y accesible, los frutos del conocimiento y del saber acumulados hasta entonces bajo la crítica y tamiz de la <a href="/wiki/Raz%C3%B3n" title="Razón">razón</a>. Además, expone la ideología <a href="/wiki/Laicismo" title="Laicismo">laicista</a>, <a href="/wiki/Pragmatismo" title="Pragmatismo">pragmática</a> y <a href="/wiki/Materialismo" title="Materialismo">materialista</a> de la Ilustración <a href="/wiki/Burgues%C3%ADa" title="Burguesía">burguesa</a> . Contiene 72 000 artículos de más de 140 colaboradores, entre ellos <a href="/wiki/Voltaire" title="Voltaire">Voltaire</a>, <a href="/wiki/Rousseau" class="mw-redirect" title="Rousseau">Rousseau</a>, <a href="/wiki/Condillac" title="Condillac">Condillac</a>, el barón de <a href="/wiki/Holbach" class="mw-redirect" title="Holbach">Holbach</a> o <a href="/wiki/Turgot" class="mw-redirect" title="Turgot">Turgot</a>, por citar algunos.</li>
<li>1753: Traducción ampliada por <a href="/wiki/Jos%C3%A9_Antonio_Miravel_y_Herrera" title="José Antonio Miravel y Herrera">José Antonio Miravel y Herrera</a> de <i>El gran diccionario historico, o miscellanea curiosa...</i> de <a href="/wiki/Louis_Mor%C3%A9ri" title="Louis Moréri">Louis Moréri</a> , en diez volúmenes.</li>
<li>1768-1771: <i><a href="/wiki/Enciclopedia_Brit%C3%A1nica" title="Enciclopedia Británica">Enciclopedia Británica</a></i>, publicada originalmente por Adam y Charles Black. Se reimprimió en papel hasta el año 2012; las ediciones más famosas fueron la novena (1875-1889) y la undécima (1911) por su erudición y estilo literario. La última edición, decimoquinta (2010), se divide en 3 partes: una <i>Micropædia</i> de 12 volúmenes de artículos cortos (menos de 750 palabras), una <i>Macropædia</i> de 17 volúmenes de artículos largos (entre 2 y 310 páginas) y una <i>Propædia</i> en un solo volumen que ofrece un esquema jerárquico del conocimiento humano.</li>
<li>1770-1776: <i><a href="/wiki/Encyclop%C3%A9die_ou_dictionnaire_universel_raisonn%C3%A9_des_connaissances_humaines" class="mw-redirect" title="Encyclopédie ou dictionnaire universel raisonné des connaissances humaines">Encyclopédie ou dictionnaire universel raisonné des connaissances humaines</a></i> . 42 volúmenes y 6 suplementos. Yverdon 1770-1776, también llamada <i>Enciclopedia de Yverdon</i>, por Fortunato Felice.</li>
<li>1773-1781: <a href="/wiki/Siku_Quanshu" title="Siku Quanshu">Siku Quanshu</a> (四庫全書 en chino tradicional, 四库全书 en chino simplificado, <i>Biblioteca completa en cuatro partes</i>) es una biblioteca enciclopédica de libros chinos compuesta en el siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XVIII</span> durante la <a href="/wiki/Dinast%C3%ADa_Qing" title="Dinastía Qing">dinastía Qing</a> por edicto del emperador <a href="/wiki/Qianlong" title="Qianlong">Qianlong</a>.</li>
<li>1778-1792: <i>Idea dell'Universo</i> del conquense <a href="/wiki/Lorenzo_Herv%C3%A1s_y_Panduro" class="mw-redirect" title="Lorenzo Hervás y Panduro">Lorenzo Hervás y Panduro</a> , 21 volúmenes, traducidos por el propio autor al castellano e impresos en España.</li>
<li>1782-1832: <i><a href="/wiki/Encyclop%C3%A9die_M%C3%A9thodique" class="mw-redirect" title="Encyclopédie Méthodique">Encyclopédie Méthodique</a></i>, enciclopedia temática de <a href="/wiki/Charles-Joseph_Panckoucke" title="Charles-Joseph Panckoucke">Charles-Joseph Panckoucke</a> en 206 volúmenes, 157 de texto a dos columnas y 53 de láminas, traducida en parte al español por iniciativa del impresor alcarreño <a href="/wiki/Antonio_de_Sancha" title="Antonio de Sancha">Antonio de Sancha</a>.</li></ul>
<p>Después del desarrollo de la <a href="/wiki/Revoluci%C3%B3n_francesa" title="Revolución francesa">Revolución francesa</a>, se publicaron estos libros:
</p>
<ul><li>1796-1808: <i>Conversations-Lexikon mit vorzüglicher Rücksicht auf die gegenwärtigen Zeiten</i> de Renatus Gotthelf Löbel y Christian Wilhelm Franke, publicada en <a href="/wiki/Leipzig" title="Leipzig">Leipzig</a>. Su segunda edición (1812-1819) es ya la <i><a href="/wiki/Enciclopedia_Brockhaus" title="Enciclopedia Brockhaus">Enciclopedia Brockhaus</a></i>.</li>
<li>1828: <i>Diccionario histórico enciclopédico</i> de <a href="/wiki/Vicente_Joaqu%C3%ADn_Bast%C3%BAs" class="mw-redirect" title="Vicente Joaquín Bastús">Vicente Joaquín Bastús</a> (Barcelona: Imp. de Roca), 4 volúmenes y un <i>Suplemento</i>; se reimprimió también en 1833.</li>
<li>1842: <i>Manual enciclopédico o repertorio universal de noticias interesantes, curiosas e instructivas sobre diferentes materias útil a toda clase de personas</i> (Madrid: Ignacio Boix). Es una enciclopedia temática de unos 360 artículos distintos escrita por un desconocido José Vanderlepe, quizá pseudónimo de Crispín de Eyalieta.</li>
<li>1847-1853: <i>Encyclopédie moderne. Dictionnaire abrégé des sciences, des lettres, des arts, de l'industrie, de l'agriculture et du commerce</i> (París: Firmin Didot Frères, 1847-1853, 30 volúmenes), dirigida por <a href="/wiki/L%C3%A9on_Renier" title="Léon Renier">Léon Renier</a>.</li>
<li>1840-1855: <i>Diccionario enciclopédico</i> de Joseph Meyer, publicado por la editorial Bibliographisches Institut, en 52 volúmenes.</li>
<li>1851-1855: <i><a href="/wiki/Enciclopedia_moderna" title="Enciclopedia moderna">Enciclopedia Moderna. Diccionario universal de literatura, ciencia, arte, agricultura, industria y comercio</a></i> (Madrid: 1851-1855 , 37 volúmenes), de <a href="/wiki/Francisco_de_Paula_Mellado" title="Francisco de Paula Mellado">Francisco de Paula Mellado</a>.</li>
<li>1866-1876: <a href="/wiki/Grand_Dictionnaire_universel_du_XIXe_si%C3%A8cle" title="Grand Dictionnaire universel du XIXe siècle">Grand Dictionnaire universel du XIXe siècle</a>, primera edición de la  enciclopedia diccionario de Larousse, en francés, 17 volúmenes</li>
<li>1882-1886: Enciclopedia Popular Ilustrada de Ciencias y Artes  - Autor: Federico Gillman (Madrid, Gras y Cía., 1882), 8 volúmenes.</li>
<li>1887-1889: <i><a href="/wiki/Diccionario_Enciclop%C3%A9dico_Hispano-Americano_de_Literatura,_Ciencias_y_Artes" class="mw-redirect" title="Diccionario Enciclopédico Hispano-Americano de Literatura, Ciencias y Artes">Diccionario Enciclopédico Hispano-Americano de Literatura, Ciencias y Artes</a></i>, Barcelona: Montaner y Simón, 25 tomos en 26 volúmenes.</li>
<li>1910:  Enciclopedia ilustrada Segui: Diccionario Universal con todas las voces y locuciones usadas en España y en la América Latina (Barcelona, Seguí, 1910)  (14 volúmenes).</li>
<li>1908-1930: <i><a href="/wiki/Enciclopedia_universal_ilustrada_europeo-americana" class="mw-redirect" title="Enciclopedia universal ilustrada europeo-americana">Enciclopedia universal ilustrada europeo-americana</a></i> de <a href="/wiki/Editorial_Espasa-Calpe" class="mw-redirect" title="Editorial Espasa-Calpe">Editorial Espasa-Calpe</a> , en 70 volúmenes, más numerosos apéndices, de forma que, en 2012, contaba con 119 tomos en 122 volúmenes.</li></ul>
<div class="mw-heading mw-heading4"><h4 id="América_Latina"><span id="Am.C3.A9rica_Latina"></span>América Latina</h4><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=5" title="Editar sección: América Latina"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<p>En el siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XVI</span> cuando se imprimen los verdaderos documentos de referencia gracias a la llegada de la <a href="/wiki/Imprenta" title="Imprenta">imprenta</a> a América se inician la distribución en el nuevo continente. Una de las primeras enciclopedias de esta época fue la <i><a href="/wiki/Historia_general_de_las_cosas_de_la_Nueva_Espa%C3%B1a" class="mw-redirect" title="Historia general de las cosas de la Nueva España">Historia general de las cosas de la Nueva España</a></i> de fray <a href="/wiki/Bernardino_de_Sahag%C3%BAn" title="Bernardino de Sahagún">Bernardino de Sahagún</a>. Se tiene también la <i>Biblioteca Hispanoamérica Septentorial</i> de José Mariano Beristáin.
</p><p>Obras españolas importantes sobre <a href="/wiki/Am%C3%A9rica_Latina" title="América Latina">América Latina</a> fueron el <i><a href="/wiki/Diccionario_Enciclop%C3%A9dico_Hispano_Americano" class="mw-redirect" title="Diccionario Enciclopédico Hispano Americano">Diccionario Enciclopédico Hispano Americano</a></i> en 28 volúmenes (1883-1910) y la <i><a href="/wiki/Enciclopedia_universal_ilustrada_europeo-americana" class="mw-redirect" title="Enciclopedia universal ilustrada europeo-americana">Enciclopedia universal ilustrada europeo-americana</a></i>.
</p>
<div class="mw-heading mw-heading3"><h3 id="Fines_del_siglo_XX_y_actualidad">Fines del siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XX</span> y actualidad</h3><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=6" title="Editar sección: Fines del siglo&nbsp;XX y actualidad"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<div class="noprint AP rellink"><span style="font-size:88%">Artículo principal:</span> <i><a href="/wiki/Enciclopedia_en_l%C3%ADnea" title="Enciclopedia en línea"> Enciclopedia en línea</a></i></div>
<p>Con el tiempo, se ha derivado la incorporación de contenido en <a href="/wiki/Almacenamiento_vital_digital" title="Almacenamiento vital digital">Almacenamiento vital digital</a>. El <a href="/wiki/Proyecto_Gutenberg" title="Proyecto Gutenberg">proyecto Gutenberg</a> incentivó en la recopilación de datos antiguos.
</p>
<div class="mw-heading mw-heading2"><h2 id="Principales_enciclopedias_modernas">Principales enciclopedias modernas</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=7" title="Editar sección: Principales enciclopedias modernas"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<p>Las principales enciclopedias modernas son:
</p>
<ul><li>De habla española, la <i><a href="/wiki/Enciclopedia_Espasa" title="Enciclopedia Espasa">Enciclopedia Espasa</a></i>, <i><a href="/wiki/Diccionario_Enciclop%C3%A9dico_Hispano-Americano_de_Literatura,_Ciencias_y_Artes" class="mw-redirect" title="Diccionario Enciclopédico Hispano-Americano de Literatura, Ciencias y Artes">Diccionario Enciclopédico Hispano-Americano de Literatura, Ciencias y Artes</a></i> y el <i>Gran diccionario enciclopédico universal</i>; todas de origen hispano y concebidas para su utilización americana y europea en el siglo&nbsp;<span style="font-variant:small-caps;text-transform:lowercase">XX</span>.</li>
<li>De habla inglesa, la <i><a href="/wiki/Enciclopedia_Brit%C3%A1nica" title="Enciclopedia Británica">Enciclopedia Británica</a></i> y la <i>Enciclopedia Británica Online</i>; enciclopedia en inglés más antigua (1768). El 13 de marzo de 2012 se anunció que dejaría de imprimirse en papel y se conservaría únicamente la versión en línea, que comenzó en 1994.</li>
<li>De habla francesa, la <i><a href="/wiki/Enciclopedia_Larousse" title="Enciclopedia Larousse">Enciclopedia Larousse</a></i> (<i>Grand Larousse</i>) y <i>Encyclopedia Universalis</i>; de alto reconocimiento y editada la primera por Larousse han sido de gran aceptación en el mundo.</li>
<li>De habla alemana, la <i><a href="/wiki/Enciclopedia_Brockhaus" title="Enciclopedia Brockhaus">Enciclopedia Brockhaus</a></i> (<i>Brockhaus Encyclopädie</i>); la más completa de las enciclopedias alemanas con 260&nbsp;000 entradas en 17&nbsp;000 páginas.</li>
<li>De habla italiana, la <i><a href="/wiki/Enciclopedia_Treccani" title="Enciclopedia Treccani">Enciclopedia Treccani</a></i>, la mayor de origen italiano, que cuenta con 35 volúmenes.</li>
<li>De habla portuguesa, <i>Grande enciclopédia portuguesa e brasileira</i>.</li>
<li>De habla rusa, la <i><a href="/wiki/Gran_Enciclopedia_Sovi%C3%A9tica" title="Gran Enciclopedia Soviética">Gran Enciclopedia Soviética</a></i> (<i>Bolshaya Sovietskaya Entsiklopediya</i>); una de las más extensas publicaciones de saber en idioma <a href="/wiki/Lenguas_eslavas" title="Lenguas eslavas">eslavo</a>.</li></ul>
<p>Entre las temáticas destacan: <i><a href="/wiki/Enciclopedia_Cat%C3%B3lica" title="Enciclopedia Católica">Catholic Encyclopedia</a></i>, <i>New Catholic Encyclopaedia</i>, <i><a href="/wiki/Encyclopaedia_Judaica" title="Encyclopaedia Judaica">Encyclopaedia Judaica</a></i>, <i><a href="/wiki/Encyclopaedia_of_Islam" title="Encyclopaedia of Islam">Encyclopaedia of Islam</a></i>, <i><a href="/wiki/Realencyclop%C3%A4die_der_classischen_Altertumswissenschaft" title="Realencyclopädie der classischen Altertumswissenschaft">Realencyclopädie der classischen Altertumswissenschaft</a></i>, <i><a href="/wiki/Enciclopedia_de_la_Vida" class="mw-redirect" title="Enciclopedia de la Vida">Enciclopedia de la Vida</a> </i> y <i>Enciclopedia del Derecho</i>.
</p><p>Con el advenimiento de la <a href="/wiki/Inform%C3%A1tica" title="Informática">informática</a> han surgido las enciclopedias <a href="/wiki/Multimedia" title="Multimedia">multimedia</a> que a la tradicional información textual y pictórica añaden elementos <a href="/wiki/Audiovisual" title="Audiovisual">audiovisuales</a>. Ejemplos de estas son <i>Enciclopedia Británica</i>, <i><a href="/wiki/Encarta" class="mw-redirect" title="Encarta">Encarta</a></i>, <i><a href="/wiki/Enciclonet" title="Enciclonet">Enciclonet</a></i> y <i><a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></i>, que pueden consultarse por medio de discos ópticos o directamente en <a href="/wiki/Internet" title="Internet">Internet</a>.
</p>
<div class="mw-heading mw-heading3"><h3 id="Las_enciclopedias_virtuales">Las enciclopedias virtuales</h3><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=8" title="Editar sección: Las enciclopedias virtuales"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<figure class="mw-default-size" typeof="mw:File/Thumb"><a href="/wiki/Archivo:Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png" class="mw-file-description"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png/220px-Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png" decoding="async" width="220" height="176" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png/330px-Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/53/Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png/440px-Chybn%C3%A9_zobrazov%C3%A1n%C3%AD_referenc%C3%AD.png 2x" data-file-width="1280" data-file-height="1024"></a><figcaption>Captura de pantalla de <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a> en <a href="/wiki/Idioma_checo" title="Idioma checo">idioma checo</a>. Wikipedia es la enciclopedia más consultada de Internet<sup id="cite_ref-9" class="reference separada"><a href="#cite_note-9"><span class="corchete-llamada">[</span>9<span class="corchete-llamada">]</span></a></sup>​<sup id="cite_ref-Woodson_10-0" class="reference separada"><a href="#cite_note-Woodson-10"><span class="corchete-llamada">[</span>10<span class="corchete-llamada">]</span></a></sup>​<sup id="cite_ref-AlexaTop500_11-0" class="reference separada"><a href="#cite_note-AlexaTop500-11"><span class="corchete-llamada">[</span>11<span class="corchete-llamada">]</span></a></sup>​ y la más fiable en cuanto a sus contenidos.<sup id="cite_ref-12" class="reference separada"><a href="#cite_note-12"><span class="corchete-llamada">[</span>12<span class="corchete-llamada">]</span></a></sup>​</figcaption></figure>
<div class="VT rellink"><span style="font-size:88%">Véase también:</span> <i><a href="/wiki/Tecnolog%C3%ADa_de_la_informaci%C3%B3n" title="Tecnología de la información">Tecnología de la información</a></i></div>
<p>El primer <a href="/wiki/Sitio_web" title="Sitio web">sitio web</a> enciclopédico fue <a href="/wiki/Interpedia" title="Interpedia">Interpedia</a>, creado en octubre de 1993 por <a href="/wiki/Rick_Gates" title="Rick Gates">Rick Gates</a>.<sup id="cite_ref-13" class="reference separada"><a href="#cite_note-13"><span class="corchete-llamada">[</span>13<span class="corchete-llamada">]</span></a></sup>​ Las enciclopedias <a href="/wiki/Multimedia" title="Multimedia">electrónicas</a> <a href="/wiki/Revisi%C3%B3n_por_pares" title="Revisión por pares">revisadas por expertos</a> en español más extensas son: <a href="/wiki/Enciclonet" title="Enciclonet">Enciclonet</a>,<sup id="cite_ref-14" class="reference separada"><a href="#cite_note-14"><span class="corchete-llamada">[</span>14<span class="corchete-llamada">]</span></a></sup>​ de la editorial <a href="/wiki/Micronet" class="mw-redirect" title="Micronet">Micronet</a>, en edición continua, y su versión en <a href="/wiki/DVD-ROM" title="DVD-ROM">DVD-ROM</a>: <a href="/wiki/Enciclopedia_Universal_Micronet" title="Enciclopedia Universal Micronet">Enciclopedia Universal Micronet</a>, publicada en <a href="/wiki/Madrid" title="Madrid">Madrid</a> desde 1995, actualmente en su 23.ª edición, con más de 185&nbsp;000 artículos.<sup id="cite_ref-15" class="reference separada"><a href="#cite_note-15"><span class="corchete-llamada">[</span>15<span class="corchete-llamada">]</span></a></sup>​
</p><p>Otros sitios web enciclopédicos son <a href="/wiki/Knol" title="Knol">Knol</a> de Google, la <i><a href="/wiki/Stanford_Encyclopedia_of_Philosophy" title="Stanford Encyclopedia of Philosophy">Stanford Encyclopedia of Philosophy</a></i> y la Enciclopedia del Derecho. Un elemento crítico en la evolución de las enciclopedias virtuales fue la inclusión de contenido abierto, iniciada por <a href="/wiki/GNUpedia" class="mw-redirect" title="GNUpedia">GNUpedia</a> y continuada por su bifurcación <a href="/wiki/Nupedia" title="Nupedia">Nupedia</a> bajo la empresa <a href="/wiki/Bomis" title="Bomis">Bomis</a>. Tiempo después, se desarrollaron las ediciones <a href="/wiki/Wiki" title="Wiki">wiki</a> con <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a> y <a href="/wiki/Fandom_(sitio_web)" title="Fandom (sitio web)">Fandom</a>.
</p><p>Adicionalmente, se elaboró  <i><a href="/wiki/Software" title="Software">software</a></i> con contenido enciclopédico, y ejemplos de ello la <a href="/wiki/Encyclop%C3%A6dia_Britannica_Ultimate_Reference_Suite" class="mw-redirect" title="Encyclopædia Britannica Ultimate Reference Suite">versión suite</a> de la <i><a href="/wiki/Enciclopedia_Brit%C3%A1nica" title="Enciclopedia Británica">Enciclopedia Británica</a></i> o la desaparecida <i><a href="/wiki/Microsoft_Encarta" title="Microsoft Encarta">Microsoft Encarta</a></i>.
</p>
<div class="mw-heading mw-heading2"><h2 id="Véase_también"><span id="V.C3.A9ase_tambi.C3.A9n"></span>Véase también</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=9" title="Editar sección: Véase también"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<div class="columns" style="-moz-column-count:2; -webkit-column-count:2; column-count:2;">
<ul><li><a href="/wiki/Categor%C3%ADa:Enciclopedias" title="Categoría:Enciclopedias">Categoría:Enciclopedias</a></li>
<li><a href="/wiki/Diccionario" title="Diccionario">Diccionario</a></li>
<li><a href="/wiki/Tesauro" title="Tesauro">Tesauro</a></li>
<li><a href="/wiki/Enciclopedias_en_espa%C3%B1ol" class="mw-redirect" title="Enciclopedias en español">Lista de enciclopedias en español</a></li>
<li><a href="/wiki/Enciclopedias_en_ingl%C3%A9s" title="Enciclopedias en inglés">Lista de enciclopedias en inglés</a></li>
<li><a href="/wiki/Poliantea" title="Poliantea">Poliantea</a></li>
<li><a href="/wiki/Enciclopedismo" title="Enciclopedismo">Enciclopedismo</a></li>
<li><a href="/wiki/Enciclopedia_en_l%C3%ADnea" title="Enciclopedia en línea">Enciclopedia en línea</a></li></ul>
</div>
<div class="mw-heading mw-heading2"><h2 id="Notas">Notas</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=10" title="Editar sección: Notas"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<div class="listaref" style="list-style-type: decimal;"><ol class="references">
<li id="cite_note-1"><span class="mw-cite-backlink"><a href="#cite_ref-1" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.escolar.com/lecturas/preguntas-y-respuestas/por-que-5/que-significado-tiene.html">«¿Qué significado tiene la palabra "enciclopedia"?»</a>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=%C2%BFQu%C3%A9+significado+tiene+la+palabra+%22enciclopedia%22%3F&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Fwww.escolar.com%2Flecturas%2Fpreguntas-y-respuestas%2Fpor-que-5%2Fque-significado-tiene.html&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-2"><span class="mw-cite-backlink"><a href="#cite_ref-2" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"> <a href="/w/index.php?title=Corominas,_Joan&amp;action=edit&amp;redlink=1" class="new" title="Corominas, Joan (aún no redactado)">Corominas, Joan</a>: <i>Breve diccionario etimológico de la lengua castellana</i>.</span>
</li>
<li id="cite_note-3"><span class="mw-cite-backlink"><a href="#cite_ref-3" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20211001193023/https://www.lexico.com/es/definicion/enciclopedia">«Definicion de enciclopedia»</a>. Oxford University Press. Archivado desde <a rel="nofollow" class="external text" href="https://www.lexico.com/es/definicion/enciclopedia">el original</a> el 1 de octubre de 2021<span class="reference-accessdate">. Consultado el 1 de octubre de 2021</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Definicion+de+enciclopedia&amp;rft.genre=book&amp;rft.pub=Oxford+University+Press&amp;rft_id=https%3A%2F%2Fwww.lexico.com%2Fes%2Fdefinicion%2Fenciclopedia&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-4"><span class="mw-cite-backlink"><a href="#cite_ref-4" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><i>Enciclopedia Ilustrada Cumbre</i>, Tomo 5, página 296, <a href="/wiki/Especial:FuentesDeLibros/9683300685" class="internal mw-magiclink-isbn">ISBN 968-33-0068-5</a>.</span>
</li>
<li id="cite_note-5"><span class="mw-cite-backlink"><a href="#cite_ref-5" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20070803182506/http://library.rcc.edu/riverside/glossaryoflibraryterms.htm#e">«Encyclopedia.»</a>. Archivado desde <a rel="nofollow" class="external text" href="http://library.rcc.edu/riverside/glossaryoflibraryterms.htm#e">el original</a> el 3 de agosto de 2007.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Encyclopedia.&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Flibrary.rcc.edu%2Friverside%2Fglossaryoflibraryterms.htm%23e&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span> <i>Glossary of Library Terms</i>. Riverside City College, Digital Library/Learning Resource Center. Revisado el 23 de marzo de 1998.</span>
</li>
<li id="cite_note-6"><span class="mw-cite-backlink"><a href="#cite_ref-6" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20211019000245/https://www.lexico.com/es/definicion/diccionario">«DICCIONARIO | Definition of DICCIONARIO by Oxford Dictionary on Lexico.com also meaning of DICCIONARIO»</a>. <i>Lexico Dictionaries | Spanish</i> <span style="color:var(--color-subtle, #555 );">(en inglés)</span>. Archivado desde <a rel="nofollow" class="external text" href="https://www.lexico.com/es/definicion/diccionario">el original</a> el 19 de octubre de 2021<span class="reference-accessdate">. Consultado el 19 de octubre de 2021</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.atitle=DICCIONARIO+%7C+Definition+of+DICCIONARIO+by+Oxford+Dictionary+on+Lexico.com+also+meaning+of+DICCIONARIO&amp;rft.genre=article&amp;rft.jtitle=Lexico+Dictionaries+%7C+Spanish&amp;rft_id=https%3A%2F%2Fwww.lexico.com%2Fes%2Fdefinicion%2Fdiccionario&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-7"><span class="mw-cite-backlink"><a href="#cite_ref-7" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span id="CITAREFGozalbes_Cravioto2000" class="citation">Gozalbes Cravioto, Enrique (2000), <i>Caput celtiberiae: la tierra de Cuenca en las fuentes clásicas</i>, Univ de Castilla La Mancha, <a rel="nofollow" class="external text" href="http://books.google.com.pe/books?id=cL14XX16moIC&amp;pg=PA222">resumen divulgativo</a></span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.au=Gozalbes+Cravioto%2C+Enrique&amp;rft.aufirst=Enrique&amp;rft.aulast=Gozalbes+Cravioto&amp;rft.btitle=Caput+celtiberiae%3A+la+tierra+de+Cuenca+en+las+fuentes+cl%C3%A1sicas&amp;rft.date=2000&amp;rft.genre=book&amp;rft.pub=Univ+de+Castilla+La+Mancha&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span>.</span>
</li>
<li id="cite_note-8"><span class="mw-cite-backlink"><a href="#cite_ref-8" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20111128141905/http://tesis.ula.ve/pregrado/tde_busca/arquivo.php?codArquivo=882">«Enciclopedia y Diccionario diferencias, las enciclopedias en Internet: ventajas de una enciclopedia en impresos y la web»</a>. Biblioteca Digital de Trabajos Especiales de Grado. p.&nbsp;4. Archivado desde <a rel="nofollow" class="external text" href="http://tesis.ula.ve/pregrado/tde_busca/arquivo.php?codArquivo=882">el original</a> el 28 de noviembre de 2011<span class="reference-accessdate">. Consultado el 4 de diciembre de 2010</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Enciclopedia+y+Diccionario+diferencias%2C+las+enciclopedias+en+Internet%3A+ventajas+de+una+enciclopedia+en+impresos+y+la+web&amp;rft.genre=book&amp;rft.pages=4&amp;rft.pub=Biblioteca+Digital+de+Trabajos+Especiales+de+Grado&amp;rft_id=http%3A%2F%2Ftesis.ula.ve%2Fpregrado%2Ftde_busca%2Farquivo.php%3FcodArquivo%3D882&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-9"><span class="mw-cite-backlink"><a href="#cite_ref-9" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span id="CITAREFTancer,_Bill1_de_mayo_de_2007" class="citation publicación">Tancer, Bill (1 de mayo de 2007). <a rel="nofollow" class="external text" href="http://www.time.com/time/business/article/0,8599,1595184,00.html">«Look Who's Using Wikipedia»</a>. <i><a href="/wiki/Time" title="Time">Time</a></i><span class="reference-accessdate">. Consultado el 1 de diciembre de 2007</span>. «The sheer volume of content [...] is partly responsible for the site's dominance as an online reference. When compared to the top 3,200 educational reference sites in the U.S., Wikipedia is #1, capturing 24.3% of all visits to the category».</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.atitle=Look+Who%27s+Using+Wikipedia&amp;rft.au=Tancer%2C+Bill&amp;rft.aulast=Tancer%2C+Bill&amp;rft.date=1+de+mayo+de+2007&amp;rft.genre=article&amp;rft.jtitle=Time&amp;rft_id=http%3A%2F%2Fwww.time.com%2Ftime%2Fbusiness%2Farticle%2F0%2C8599%2C1595184%2C00.html&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&nbsp;</span></span> <a href="/wiki/Cf." class="mw-redirect" title="Cf.">Cf.</a> Bill Tancer (Global Manager, Hitwise), <a rel="nofollow" class="external text" href="http://weblogs.hitwise.com/bill-tancer/2007/03/wikipedia_search_and_school_ho.html">"Wikipedia, Search and School Homework"</a> <a rel="nofollow" class="external text" href="https://web.archive.org/web/20120325220239/http://weblogs.hitwise.com/bill-tancer/2007/03/wikipedia_search_and_school_ho.html">Archivado</a> el 25 de marzo de 2012 en <a href="/wiki/Wayback_Machine" title="Wayback Machine">Wayback Machine</a>., <i><a href="/w/index.php?title=Hitwise&amp;action=edit&amp;redlink=1" class="new" title="Hitwise (aún no redactado)">Hitwise</a></i>: An <a href="/wiki/Experian" title="Experian">Experian</a> Company (<a href="/wiki/Blog" title="Blog">Blog</a>), 1 de marzo de 2007. Consultado el 18 de diciembre de 2008.</span>
</li>
<li id="cite_note-Woodson-10"><span class="mw-cite-backlink"><a href="#cite_ref-Woodson_10-0" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span id="CITAREFAlex_Woodson8_de_julio_de_2007" class="citation publicación">Alex Woodson (8 de julio de 2007). <a rel="nofollow" class="external text" href="http://www.reuters.com/article/internetNews/idUSN0819429120070708">«Wikipedia remains go-to site for online news»</a>. <i><a href="/wiki/Reuters" title="Reuters">Reuters</a></i><span class="reference-accessdate">. Consultado el 16 de diciembre de 2007</span>. «Online encyclopedia Wikipedia has added about 20 million unique monthly visitors in the past year, making it the top online news and information destination, according to Nielsen//NetRatings.»</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.atitle=Wikipedia+remains+go-to+site+for+online+news&amp;rft.au=Alex+Woodson&amp;rft.aulast=Alex+Woodson&amp;rft.date=8+de+julio+de+2007&amp;rft.genre=article&amp;rft.jtitle=Reuters&amp;rft_id=http%3A%2F%2Fwww.reuters.com%2Farticle%2FinternetNews%2FidUSN0819429120070708&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-AlexaTop500-11"><span class="mw-cite-backlink"><a href="#cite_ref-AlexaTop500_11-0" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20090302215553/http://www.alexa.com//site//ds//top_sites?ts_mode=global&amp;lang=none">«Top 500»</a>. <a href="/wiki/Alexa_Internet" title="Alexa Internet">Alexa</a>. Archivado desde <a rel="nofollow" class="external text" href="http://www.alexa.com/site/ds/top_sites?ts_mode=global&amp;lang=none">el original</a> el 2 de marzo de 2009<span class="reference-accessdate">. Consultado el 26 de junio de 2009</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Top+500&amp;rft.genre=book&amp;rft.pub=Alexa&amp;rft_id=http%3A%2F%2Fwww.alexa.com%2Fsite%2Fds%2Ftop_sites%3Fts_mode%3Dglobal%26lang%3Dnone&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-12"><span class="mw-cite-backlink"><a href="#cite_ref-12" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text">Criado, Miguel Ángel. <a rel="nofollow" class="external text" href="http://esmateria.com/2012/08/03/la-wikipedia-sigue-siendo-mas-fiable-qu-otras-enciclopedias/">«La Wikipedia sigue siendo más fiable que otras enciclopedias.»</a> Sitio digital 'Materia', 3 de agosto de 2012.</span>
</li>
<li id="cite_note-13"><span class="mw-cite-backlink"><a href="#cite_ref-13" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20170916023256/http://listserv.uh.edu/cgi-bin/wa?A2=ind9310d&amp;L=pacs-l&amp;T=0&amp;P=1418">«PACS-L Listserv message "The Internet Encyclopedia", Oct 25, 1993»</a>. Archivado desde <a rel="nofollow" class="external text" href="http://listserv.uh.edu/cgi-bin/wa?A2=ind9310d&amp;L=pacs-l&amp;T=0&amp;P=1418">el original</a> el 16 de septiembre de 2017<span class="reference-accessdate">. Consultado el 19 de septiembre de 2012</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=PACS-L+Listserv+message+%22The+Internet+Encyclopedia%22%2C+Oct+25%2C+1993&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Flistserv.uh.edu%2Fcgi-bin%2Fwa%3FA2%3Dind9310d%26L%3Dpacs-l%26T%3D0%26P%3D1418&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-14"><span class="mw-cite-backlink"><a href="#cite_ref-14" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.enciclonet.com/">«Sitio web de Enciclonet.»</a>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Sitio+web+de+Enciclonet.&amp;rft.genre=book&amp;rft_id=http%3A%2F%2Fwww.enciclonet.com%2F&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
<li id="cite_note-15"><span class="mw-cite-backlink"><a href="#cite_ref-15" aria-label="Volver arriba" title="Volver arriba">↑</a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="ftp://ftp.micronet.es/public/fichas/EUM2013.pdf">«Ficha comercial de la Enciclopedia Universal Micronet»</a><span class="reference-accessdate">. Consultado el 26 de octubre de 2012</span>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Ficha+comercial+de+la+Enciclopedia+Universal+Micronet&amp;rft.genre=book&amp;rft_id=ftp%3A%2F%2Fftp.micronet.es%2Fpublic%2Ffichas%2FEUM2013.pdf&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></span>
</li>
</ol></div>
<div class="mw-heading mw-heading2"><h2 id="Referencias">Referencias</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=11" title="Editar sección: Referencias"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<ul><li><span class="citation libro"><i>Enciclopedia Ilustrada Cumbre</i>. Editorial Cumbre, S.A.<a href="/wiki/Especial:FuentesDeLibros/9683300685" class="internal mw-magiclink-isbn">ISBN 968-33-0068-5</a>. 1984.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.btitle=Enciclopedia+Ilustrada+Cumbre&amp;rft.date=1984&amp;rft.genre=book&amp;rft.pub=Editorial+Cumbre%2C+S.A.ISBN+968-33-0068-5&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></li>
<li><span id="CITAREFWalsh1968" class="citation libro">Walsh, S. Padraig (1968). <i>Anglo-American general encyclopedias: a historical bibliography, 1703-1967</i>. New York: Bowker. p.&nbsp;270. <small><a href="/wiki/OCLC" title="OCLC">OCLC</a>&nbsp;<a rel="nofollow" class="external text" href="//www.worldcat.org/oclc/577541">577541</a></small>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.au=Walsh%2C+S.+Padraig&amp;rft.aufirst=S.+Padraig&amp;rft.aulast=Walsh&amp;rft.btitle=Anglo-American+general+encyclopedias%3A+a+historical+bibliography%2C+1703-1967&amp;rft.date=1968&amp;rft.genre=book&amp;rft.pages=270&amp;rft.place=New+York&amp;rft.pub=Bowker&amp;rft_id=info%3Aoclcnum%2F577541&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></li>
<li><span id="CITAREFYeo2001" class="citation libro">Yeo, Richard R. (2001). <a rel="nofollow" class="external text" href="http://www.cambridge.org/us/catalogue/catalogue.asp?isbn=0521651913"><i>Encyclopaedic visions: scientific dictionaries and enlightenment culture</i></a>. Cambridge, New York: <a href="/wiki/Cambridge_University_Press" title="Cambridge University Press">Cambridge University Press</a>. <small><a href="/wiki/ISBN" title="ISBN">ISBN</a>&nbsp;<a href="/wiki/Especial:FuentesDeLibros/9780521651912" title="Especial:FuentesDeLibros/9780521651912">9780521651912</a></small>. <small><a href="/wiki/OCLC" title="OCLC">OCLC</a>&nbsp;<a rel="nofollow" class="external text" href="//www.worldcat.org/oclc/45828872">45828872</a></small>.</span><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fes.wikipedia.org%3AEnciclopedia&amp;rft.au=Yeo%2C+Richard+R.&amp;rft.aufirst=Richard+R.&amp;rft.aulast=Yeo&amp;rft.btitle=Encyclopaedic+visions%3A+scientific+dictionaries+and+enlightenment+culture&amp;rft.date=2001&amp;rft.genre=book&amp;rft.isbn=9780521651912&amp;rft.place=Cambridge%2C+New+York&amp;rft.pub=Cambridge+University+Press&amp;rft_id=http%3A%2F%2Fwww.cambridge.org%2Fus%2Fcatalogue%2Fcatalogue.asp%3Fisbn%3D0521651913&amp;rft_id=info%3Aoclcnum%2F45828872&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&nbsp;</span></span></li></ul>
<div class="mw-heading mw-heading2"><h2 id="Enlaces_externos">Enlaces externos</h2><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Enciclopedia&amp;action=edit&amp;section=12" title="Editar sección: Enlaces externos"><span>editar</span></a><span class="mw-editsection-bracket">]</span></span></div>
<ul><li><span typeof="mw:File"><span><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Wiktionary-logo.svg/20px-Wiktionary-logo.svg.png" decoding="async" width="20" height="19" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Wiktionary-logo.svg/30px-Wiktionary-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Wiktionary-logo.svg/40px-Wiktionary-logo.svg.png 2x" data-file-width="370" data-file-height="350"></span></span> <a href="/wiki/Wikcionario" title="Wikcionario">Wikcionario</a>  tiene definiciones y otra información sobre <b><a href="https://es.wiktionary.org/wiki/enciclopedia" class="extiw" title="wikt:enciclopedia">enciclopedia</a></b>.</li>
<li>Los diez primeros idiomas de Wikipedia en Internet:
<ul><li><a class="external text" href="https://www.wikipedia.org">Estadística de artículos</a></li></ul></li>
<li>Enciclopedias en Internet en inglés:
<ul><li><a rel="nofollow" class="external text" href="//www.Wikipedia.org/">Wikipedia</a></li>
<li><a rel="nofollow" class="external text" href="http://www.britannica.com">Enciclopedia Británica</a> (se requiere una cuota de suscripción para un acceso completo)</li></ul></li>
<li>Enciclopedias en Internet en alemán:
<ul><li><a rel="nofollow" class="external text" href="https://web.archive.org/web/20061005085526/http://susi.e-technik.uni-ulm.de:8080/Meyers2/index/index.html">Meyers Konversations-Lexikon 4.ed. 1885-1892</a></li>
<li><a rel="nofollow" class="external text" href="https://web.archive.org/web/20070311154435/http://lexikon.meyers.de/meyers/Meyers-Meyers_Lexikon_online">Meyers Großes Taschenlexikon 10.ed.</a></li></ul></li>
<li>Enciclopedias en Internet en italiano:
<ul><li><a rel="nofollow" class="external text" href="http://www.treccani.it/">Enciclopedia Treccani</a></li></ul></li>
<li>Enciclopedias en Internet en catalán:
<ul><li><a rel="nofollow" class="external text" href="http://www.enciclopedia.cat/">Gran Enciclopedia Catalana</a></li></ul></li>
<li>Enciclopedias en Internet en portugués:
<ul><li><a rel="nofollow" class="external text" href="http://www.infopedia.pt/">Infopedia</a></li></ul></li>
<li>Enciclopedias en Internet en francés:
<ul><li><a rel="nofollow" class="external text" href="http://www.larousse.fr/encyclopedie">Enciclopedia Larousse</a></li></ul></li>
<li>Enciclopedias en Internet en ruso:
<ul><li><a rel="nofollow" class="external text" href="http://www.brandpedia.ru/">Brandpedia</a></li></ul></li>
<li>Enciclopedias en Internet de temáticas varias:
<ul><li><a rel="nofollow" class="external text" href="http://www.open-site.org/">Open Site</a></li>
<li><a rel="nofollow" class="external text" href="http://www.encyclopedia.com">Columbia Concise</a></li>
<li><a rel="nofollow" class="external text" href="http://auth.grolier.com/cgi-bin/authV2">Grolier</a></li>
<li><a rel="nofollow" class="external text" href="http://www.comptons.com/encyclopedia/home.html">Comptons</a></li>
<li><a rel="nofollow" class="external text" href="http://plato.stanford.edu">Stanford Encyclopedia of Philosophy</a></li>
<li><a rel="nofollow" class="external text" href="http://www.utm.edu/research/iep/">Internet Encyclopedia of Philosophy</a> <a rel="nofollow" class="external text" href="https://web.archive.org/web/20091027230958/http://www.utm.edu/research/iep/">Archivado</a> el 27 de octubre de 2009 en <a href="/wiki/Wayback_Machine" title="Wayback Machine">Wayback Machine</a>.</li>
<li><a rel="nofollow" class="external text" href="http://www.iep.utm.edu/">Internet Encyclopaedia</a></li>
<li><a rel="nofollow" class="external text" href="https://web.archive.org/web/20070706121700/http://www.eol.org//home.html">EOL. Enciclopedia de la vida</a></li>
<li><a rel="nofollow" class="external text" href="http://www.leyderecho.org/">Enciclopedia del Derecho (por países)</a></li></ul></li></ul>
<style data-mw-deduplicate="TemplateStyles:r161257576">.mw-parser-output .mw-authority-control{margin-top:1.5em}.mw-parser-output .mw-authority-control .navbox table{margin:0}.mw-parser-output .mw-authority-control .navbox hr:last-child{display:none}.mw-parser-output .mw-authority-control .navbox+.mw-mf-linked-projects{display:none}.mw-parser-output .mw-authority-control .mw-mf-linked-projects{display:flex;padding:0.5em;border:1px solid var(--border-color-base,#a2a9b1);background-color:var(--background-color-neutral,#eaecf0);color:var(--color-base,#202122)}.mw-parser-output .mw-authority-control .mw-mf-linked-projects ul li{margin-bottom:0}.mw-parser-output .mw-authority-control .navbox{border:1px solid var(--border-color-base,#a2a9b1);background-color:var(--background-color-neutral-subtle,#f8f9fa)}.mw-parser-output .mw-authority-control .navbox-list{border-color:#f8f9fa}.mw-parser-output .mw-authority-control .navbox th{background-color:#eeeeff}html.skin-theme-clientpref-night .mw-parser-output .mw-authority-control .mw-mf-linked-projects{border:1px solid var(--border-color-base,#72777d);background-color:var(--background-color-neutral,#27292d);color:var(--color-base,#eaecf0)}html.skin-theme-clientpref-night .mw-parser-output .mw-authority-control .navbox{border:1px solid var(--border-color-base,#72777d)!important;background-color:var(--background-color-neutral-subtle,#202122)!important}html.skin-theme-clientpref-night .mw-parser-output .mw-authority-control .navbox-list{border-color:#202122!important}html.skin-theme-clientpref-night .mw-parser-output .mw-authority-control .navbox th{background-color:#27292d!important}@media(prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .mw-authority-control .mw-mf-linked-projects{border:1px solid var(--border-color-base,#72777d)!important;background-color:var(--background-color-neutral,#27292d)!important;color:var(--color-base,#eaecf0)!important}html.skin-theme-clientpref-os .mw-parser-output .mw-authority-control .navbox{border:1px solid var(--border-color-base,#72777d)!important;background-color:var(--background-color-neutral-subtle,#202122)!important}html.skin-theme-clientpref-os .mw-parser-output .mw-authority-control .navbox-list{border-color:#202122!important}html.skin-theme-clientpref-os .mw-parser-output .mw-authority-control .navbox th{background-color:#27292d!important}}</style><div class="mw-authority-control"><div role="navigation" class="navbox" aria-label="Navbox" style="width: inherit;padding:3px"><table class="hlist navbox-inner" style="border-spacing:0;background:transparent;color:inherit"><tbody><tr><th scope="row" class="navbox-group" style="width: 12%; text-align:center;"><a href="/wiki/Control_de_autoridades" title="Control de autoridades">Control de autoridades</a></th><td class="navbox-list navbox-odd" style="text-align:left;border-left-width:2px;border-left-style:solid;width:100%;padding:0px"><div style="padding:0em 0.25em">
<ul><li><b>Proyectos Wikimedia</b></li>
<li><span style="white-space:nowrap;"><span typeof="mw:File"><a href="/wiki/Wikidata" title="Wikidata"><img alt="Wd" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/20px-Wikidata-logo.svg.png" decoding="async" width="20" height="11" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/30px-Wikidata-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/40px-Wikidata-logo.svg.png 2x" data-file-width="1050" data-file-height="590"></a></span> Datos:</span> <span class="uid"><a href="https://www.wikidata.org/wiki/Q5292" class="extiw" title="wikidata:Q5292">Q5292</a></span></li>
<li><span style="white-space:nowrap;"><span typeof="mw:File"><a href="/wiki/Wikimedia_Commons" title="Commonscat"><img alt="Commonscat" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/15px-Commons-logo.svg.png" decoding="async" width="15" height="20" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/23px-Commons-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/30px-Commons-logo.svg.png 2x" data-file-width="1024" data-file-height="1376"></a></span> Multimedia:</span> <span class="uid"><span class="plainlinks"><a class="external text" href="https://commons.wikimedia.org/wiki/Category:Encyclopedias">Encyclopedias</a></span> / <span class="plainlinks"><a class="external text" href="https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&amp;search=%22Q5292%22">Q5292</a></span></span></li></ul>
<hr>
<ul><li><b>Identificadores</b></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Biblioteca_Nacional_de_Espa%C3%B1a" title="Biblioteca Nacional de España">BNE</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://datos.bne.es/resource/XX4344163">XX4344163</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Biblioteca_Nacional_de_Francia" title="Biblioteca Nacional de Francia">BNF</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://catalogue.bnf.fr/ark:/12148/cb12043290b">12043290b</a> <a rel="nofollow" class="external text" href="http://data.bnf.fr/ark:/12148/cb12043290b">(data)</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Gemeinsame_Normdatei" title="Gemeinsame Normdatei">GND</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://d-nb.info/gnd/4014986-9">4014986-9</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Library_of_Congress_Control_Number" title="Library of Congress Control Number">LCCN</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://id.loc.gov/authorities/sh99001614">sh99001614</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Biblioteca_Nacional_de_la_Dieta" title="Biblioteca Nacional de la Dieta">NDL</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://id.ndl.go.jp/auth/ndlna/00563841">00563841</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Biblioteca_Nacional_de_la_Rep%C3%BAblica_Checa" title="Biblioteca Nacional de la República Checa">NKC</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://aleph.nkp.cz/F/?func=find-c&amp;local_base=aut&amp;ccl_term=ica=ph117188">ph117188</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Biblioteca_Nacional_de_Israel" title="Biblioteca Nacional de Israel">NLI</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="http://olduli.nli.org.il/F/?func=find-b&amp;local_base=NLX10&amp;find_code=UID&amp;request=987007543344005171">987007543344005171</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Art_%26_Architecture_Thesaurus" title="Art &amp; Architecture Thesaurus">AAT</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://www.getty.edu/vow/AATFullDisplay?find=&amp;logic=AND&amp;note=&amp;subjectid=300129439">300129439</a></span></li>
<li><b>Diccionarios y enciclopedias</b></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Diccionario_hist%C3%B3rico_de_Suiza" title="Diccionario histórico de Suiza">DHS</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://hls-dhs-dss.ch/de/articles/028704">028704</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Enciclopedia_Brit%C3%A1nica" title="Enciclopedia Británica">Britannica</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://www.britannica.com/topic/encyclopaedia">url</a></span></li>
<li><b>Identificadores médicos</b></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Medical_Subject_Headings" title="Medical Subject Headings">MeSH</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://meshb.nlm.nih.gov/record/ui?ui=D019500">D019500</a></span></li>
<li><span style="white-space:nowrap;"><a href="/wiki/Descriptores_en_Ciencias_de_la_Salud" title="Descriptores en Ciencias de la Salud">DeCS</a>:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://decs.bvsalud.org/en/ths/resource/?id=33237">33237</a></span></li>
<li><span style="white-space:nowrap;">UMLS:</span> <span class="uid"><a rel="nofollow" class="external text" href="https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&amp;code=C0014095">C0014095</a></span></li></ul>
</div></td></tr></tbody></table></div><div class="mw-mf-linked-projects hlist">
<ul><li><span style="white-space:nowrap;"><span typeof="mw:File"><a href="/wiki/Wikidata" title="Wikidata"><img alt="Wd" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/20px-Wikidata-logo.svg.png" decoding="async" width="20" height="11" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/30px-Wikidata-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/40px-Wikidata-logo.svg.png 2x" data-file-width="1050" data-file-height="590"></a></span> Datos:</span> <span class="uid"><a href="https://www.wikidata.org/wiki/Q5292" class="extiw" title="wikidata:Q5292">Q5292</a></span></li>
<li><span style="white-space:nowrap;"><span typeof="mw:File"><a href="/wiki/Wikimedia_Commons" title="Commonscat"><img alt="Commonscat" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/15px-Commons-logo.svg.png" decoding="async" width="15" height="20" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/23px-Commons-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/30px-Commons-logo.svg.png 2x" data-file-width="1024" data-file-height="1376"></a></span> Multimedia:</span> <span class="uid"><span class="plainlinks"><a class="external text" href="https://commons.wikimedia.org/wiki/Category:Encyclopedias">Encyclopedias</a></span> / <span class="plainlinks"><a class="external text" href="https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&amp;search=%22Q5292%22">Q5292</a></span></span></li></ul>
</div></div>
</div><!--esi <esi:include src="/esitest-fa8a495983347898/content" /> <noscript><img src="https://login.wikimedia.org/wiki/Special:CentralAutoLogin/start?type=1x1" alt="" width="1" height="1" style="border: none; position: absolute;"></noscript>
<div class="printfooter" data-nosnippet="">Obtenido de «<a dir="ltr" href="https://es.wikipedia.org/w/index.php?title=Enciclopedia&amp;oldid=162961767">https://es.wikipedia.org/w/index.php?title=Enciclopedia&amp;oldid=162961767</a>»</div></div>
					<div id="catlinks" class="catlinks" data-mw="interface"><div id="mw-normal-catlinks" class="mw-normal-catlinks"><a href="/wiki/Especial:Categor%C3%ADas" title="Especial:Categorías">Categoría</a>: <ul><li><a href="/wiki/Categor%C3%ADa:Enciclopedias" title="Categoría:Enciclopedias">Enciclopedias</a></li></ul></div><div id="mw-hidden-catlinks" class="mw-hidden-catlinks mw-hidden-cats-hidden">Categorías ocultas: <ul><li><a href="/wiki/Categor%C3%ADa:Wikipedia:P%C3%A1ginas_con_enlaces_m%C3%A1gicos_de_ISBN" title="Categoría:Wikipedia:Páginas con enlaces mágicos de ISBN">Wikipedia:Páginas con enlaces mágicos de ISBN</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_texto_en_griego_antiguo" title="Categoría:Wikipedia:Artículos con texto en griego antiguo">Wikipedia:Artículos con texto en griego antiguo</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_identificadores_BNE" title="Categoría:Wikipedia:Artículos con identificadores BNE">Wikipedia:Artículos con identificadores BNE</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_identificadores_BNF" title="Categoría:Wikipedia:Artículos con identificadores BNF">Wikipedia:Artículos con identificadores BNF</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_identificadores_GND" title="Categoría:Wikipedia:Artículos con identificadores GND">Wikipedia:Artículos con identificadores GND</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_identificadores_LCCN" title="Categoría:Wikipedia:Artículos con identificadores LCCN">Wikipedia:Artículos con identificadores LCCN</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Art%C3%ADculos_con_identificadores_AAT" title="Categoría:Wikipedia:Artículos con identificadores AAT">Wikipedia:Artículos con identificadores AAT</a></li><li><a href="/wiki/Categor%C3%ADa:Wikipedia:Control_de_autoridades_con_15_elementos" title="Categoría:Wikipedia:Control de autoridades con 15 elementos">Wikipedia:Control de autoridades con 15 elementos</a></li></ul></div></div>
				</div> 